import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { createHmac } from 'crypto';
import { Repository } from 'typeorm';
import { jwtSecret, publicBaseUrl } from '../config/local-config';
import { WorkspaceService } from '../workspace/workspace.service';
import { CreateEmailCampaignDto, CreateEmailContactDto, EmailBounceDto, UpdateEmailContactDto } from './email.dto';
import { EmailCampaignEntity, EmailContactEntity, EmailDeliveryEntity } from './email.entity';

@Injectable()
export class EmailService {
  constructor(@InjectRepository(EmailContactEntity) private contacts:Repository<EmailContactEntity>, @InjectRepository(EmailCampaignEntity) private campaigns:Repository<EmailCampaignEntity>, @InjectRepository(EmailDeliveryEntity) private deliveries:Repository<EmailDeliveryEntity>, private workspace:WorkspaceService) {}

  async listContacts(userId:string,page=1,query='',status='all') { const take=50; const qb=this.contacts.createQueryBuilder('contact').where('contact.userId = :userId',{userId}); if(status!=='all')qb.andWhere('contact.status = :status',{status}); if(query.trim())qb.andWhere('(LOWER(contact.email) LIKE :query OR LOWER(contact.name) LIKE :query)',{query:`%${query.trim().toLowerCase()}%`}); const [items,total]=await qb.orderBy('contact.createdAt','DESC').skip((page-1)*take).take(take).getManyAndCount(); return{items,total,page,pages:Math.max(1,Math.ceil(total/take))}; }
  async addContact(userId:string,dto:CreateEmailContactDto){const email=dto.email.trim().toLowerCase();if(await this.contacts.exists({where:{userId,email}}))throw new ConflictException('Contato já cadastrado.');return this.contacts.save(this.contacts.create({userId,email,name:dto.name?.trim()||'',status:'subscribed',consentSource:dto.consentSource.trim(),consentAt:new Date()}));}
  async updateContact(userId:string,id:string,dto:UpdateEmailContactDto){const contact=await this.contacts.findOneBy({id,userId});if(!contact)throw new NotFoundException('Contato não encontrado.');if(dto.name!==undefined)contact.name=dto.name.trim();if(dto.status){contact.status=dto.status;contact.unsubscribedAt=dto.status==='unsubscribed'?new Date():null;if(dto.status==='subscribed')contact.consentAt=new Date();}return this.contacts.save(contact);}
  async removeContact(userId:string,id:string){const contact=await this.contacts.findOneBy({id,userId});if(!contact)throw new NotFoundException('Contato não encontrado.');await this.contacts.remove(contact);return{ok:true};}
  async listCampaigns(userId:string){return this.campaigns.find({where:{userId},order:{createdAt:'DESC'},take:100});}
  async createCampaign(userId:string,dto:CreateEmailCampaignDto){const workspace=await this.workspace.getByUserId(userId);const page:any=workspace.data.pages.find((item:any)=>item.id===dto.pageId);if(!page||(page.type!=='email'&&page.builderMode!=='email'))throw new BadRequestException('Selecione um template de e-mail salvo.');return this.campaigns.save(this.campaigns.create({userId,name:dto.name.trim(),subject:dto.subject.trim(),fromName:dto.fromName.trim(),pageId:dto.pageId,html:dto.html,status:'draft'}));}
  async sendCampaign(userId:string,id:string){const campaign=await this.campaigns.findOneBy({id,userId});if(!campaign)throw new NotFoundException('Campanha não encontrada.');if(campaign.status==='sending')throw new ConflictException('Campanha já está em processamento.');const contacts=await this.contacts.find({where:{userId,status:'subscribed'}});if(!contacts.length)throw new BadRequestException('Cadastre ao menos um contato com consentimento.');let deliveries=await this.deliveries.find({where:{campaignId:id}});if(!deliveries.length){deliveries=await this.deliveries.save(contacts.map(contact=>this.deliveries.create({campaignId:id,contactId:contact.id,email:contact.email,status:'queued'})));}campaign.status='sending';campaign.recipients=deliveries.length;await this.campaigns.save(campaign);const providerConfigured=Boolean(process.env.MAIL_DELIVERY_WEBHOOK_URL?.trim());if(!providerConfigured){campaign.status='queued';await this.campaigns.save(campaign);return{campaign,providerConfigured:false,message:'Campanha enfileirada. Configure MAIL_DELIVERY_WEBHOOK_URL para realizar a entrega.'};}for(const delivery of deliveries.filter(item=>['queued','failed'].includes(item.status)&&item.attempts<3)){await this.deliver(campaign,delivery);}await this.refreshStats(campaign);return{campaign:await this.campaigns.findOneByOrFail({id}),providerConfigured:true};}
  async open(deliveryId:string,token:string){this.assertToken(deliveryId,token);const delivery=await this.deliveries.findOneBy({id:deliveryId});if(!delivery)throw new NotFoundException();if(!delivery.openedAt){delivery.openedAt=new Date();delivery.status='opened';await this.deliveries.save(delivery);const campaign=await this.campaigns.findOneBy({id:delivery.campaignId});if(campaign)await this.refreshStats(campaign);}return{ok:true};}
  async unsubscribe(deliveryId:string,token:string){this.assertToken(deliveryId,token);const delivery=await this.deliveries.findOneBy({id:deliveryId});if(!delivery)throw new NotFoundException();const contact=await this.contacts.findOneBy({id:delivery.contactId});if(contact){contact.status='unsubscribed';contact.unsubscribedAt=new Date();await this.contacts.save(contact);}delivery.status='unsubscribed';await this.deliveries.save(delivery);return{ok:true};}
  async bounce(secret:string|undefined,dto:EmailBounceDto){const configured=process.env.MAIL_WEBHOOK_SECRET?.trim();if(!configured||secret!==configured)throw new BadRequestException('Webhook não autorizado.');const delivery=await this.deliveries.findOneBy({providerId:dto.providerId});if(!delivery)throw new NotFoundException('Entrega não encontrada.');if(dto.event==='delivered'){delivery.status='sent';delivery.sentAt=delivery.sentAt||new Date();}else{delivery.status='bounced';const contact=await this.contacts.findOneBy({id:delivery.contactId});if(contact){contact.status='bounced';await this.contacts.save(contact);}}await this.deliveries.save(delivery);const campaign=await this.campaigns.findOneBy({id:delivery.campaignId});if(campaign)await this.refreshStats(campaign);return{ok:true};}
  private token(id:string){return createHmac('sha256',jwtSecret).update(`email:${id}`).digest('hex');}
  private assertToken(id:string,token:string){if(!token||token!==this.token(id))throw new BadRequestException('Link inválido.');}
  private trackedHtml(campaign:EmailCampaignEntity,delivery:EmailDeliveryEntity){const token=this.token(delivery.id);const open=`${publicBaseUrl}/api/email/open/${delivery.id}/${token}.gif`;const unsubscribe=`${publicBaseUrl}/api/email/unsubscribe/${delivery.id}/${token}`;return `${campaign.html}<img src="${open}" width="1" height="1" alt="" style="display:none"><p style="font:12px Arial;text-align:center;color:#777"><a href="${unsubscribe}">Descadastrar</a></p>`;}
  private async deliver(campaign:EmailCampaignEntity,delivery:EmailDeliveryEntity){delivery.attempts+=1;try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);const response=await fetch(process.env.MAIL_DELIVERY_WEBHOOK_URL!,{method:'POST',headers:{'content-type':'application/json',...(process.env.MAIL_DELIVERY_TOKEN?{authorization:`Bearer ${process.env.MAIL_DELIVERY_TOKEN}`}:{})},body:JSON.stringify({to:delivery.email,subject:campaign.subject,fromName:campaign.fromName,html:this.trackedHtml(campaign,delivery),reference:delivery.id}),signal:controller.signal});clearTimeout(timeout);if(!response.ok)throw new Error(`Provedor respondeu HTTP ${response.status}`);const data:any=await response.json().catch(()=>({}));delivery.providerId=String(data.id||data.messageId||delivery.id).slice(0,255);delivery.status='sent';delivery.sentAt=new Date();delivery.error='';}catch(error){delivery.status='failed';delivery.error=String((error as Error).message||error).slice(0,1000);}await this.deliveries.save(delivery);}
  private async refreshStats(campaign:EmailCampaignEntity){const rows=await this.deliveries.find({where:{campaignId:campaign.id}});campaign.sent=rows.filter(row=>['sent','opened','unsubscribed'].includes(row.status)).length;campaign.failed=rows.filter(row=>['failed','bounced'].includes(row.status)).length;campaign.opened=rows.filter(row=>Boolean(row.openedAt)).length;campaign.status=rows.some(row=>row.status==='queued')?'queued':campaign.sent?'sent':'failed';if(campaign.status==='sent')campaign.sentAt=campaign.sentAt||new Date();await this.campaigns.save(campaign);}
}
